### ISSUE TITLE
Memory leaks on writing

### ISSUE THREAD

**Issue by mmouterde** [timescale/timescaledb#1617]
**Relevant system information:**
 - OS: Linux version 4.4.0-1090-aws (buildd@lgw01-amd64-055) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #101-Ubuntu SMP Fri Aug 2 15:21:01 UTC 2019
 - PostgreSQL version : postgres (PostgreSQL) 10.10 (Debian 10.10-1.pgdg90+1)
 - TimescaleDB version : 1.5.1
 - Installation method: `apt-get install timescaledb-1.5.1-postgresql-10`

**Describe the bug**
Memory increase continously and do not decrease once batch is finished.

**To Reproduce**
Here is an insert query.
~~~
insert into "timeseries_5dfb2122420cc9001d7e612b" ("creationCorrelationId", "date", "isText", "origin", "quantity", "textQuantity") values
  ('56296377-5436-45c2-ad07-8c2f034fd62e', '2018-02-10T10:34:30.000Z', NULL, 'import', 395.7, NULL), 
('56296377-5436-45c2-ad07-8c2f034fd62e', '2018-02-10T10:35:00.000Z', NULL, 'import', 395.7, NULL), 
('56296377-5436-45c2-ad07-8c2f034fd62e', '2018-02-10T10:35:30.000Z', NULL, 'import', 395.7, NULL), 
('56296377-5436-45c2-ad07-8c2f034fd62e', '2018-02-10T10:36:00.000Z', NULL, 'import', 395.7, NULL), 
  ...
ON CONFLICT (date) WHERE origin='import' DO UPDATE set"creationDate"=EXCLUDED."creationDate", 
  "creationCorrelationId"=EXCLUDED."creationCorrelationId", "quantity"=EXCLUDED."quantity",
  "textQuantity"=EXCLUDED."textQuantity", "isText"=EXCLUDED."isText";
~~~

Here is my schema
~~~
Table "timeseries_5dfb2122420cc9001d7e612b"
Column         |            Type             | Collation | Nullable |           Default
-----------------------+-----------------------------+-----------+----------+-----------------------------
date                  | timestamp with time zone    |           | not null |
quantity              | double precision            |           |          |
textQuantity          | text                        |           |          |
origin                | character varying(30)       |           |          |
creationCorrelationId | character varying(40)       |           |          |
creationDate          | timestamp without time zone |           |          | CURRENT_TIMESTAMP
deletionCorrelationId | character varying(40)       |           |          |
deletionDate          | timestamp without time zone |           |          |
status                | character varying(30)       |           |          | 'active'::character varying
isText                | boolean                     |           |          |
Indexes:
"unique_timeseries_5dfb2122420cc9001d7e612b" UNIQUE, btree (date) WHERE origin::text = 'import'::text
"timeseries_5dfb2122420cc9001d7e612b_date_idx" btree (date DESC)
"timeseries_5dfb2122420cc9001d7e612b_numeric_index" btree (date) WHERE status::text <> 'deleted'::text AND "isText" IS NULL
Triggers:
ts_insert_blocker BEFORE INSERT ON timeseries_5dfb2122420cc9001d7e612b FOR EACH ROW EXECUTE PROCEDURE _timescaledb_internal.insert_blocker()
~~~

Other Info : 
- global batch concern more than 600 hypetables.
- Each transaction is limited to 10MB or 100000 datapoints 
- batch transaction are sequential
- seen with @pmwkaa on slack
- timescale-tune validate the config
- SSD seem's to be the bottleneck

**Expected behavior**
- The RAM should reduce once the import is finished
- RAM should be released when no more pg client are connected

**Actual behavior**
- I have to restart database to retreive free memory
- once restarted all is ok (data are inserted, perf are OK)

**Screenshots**
![Uploading Screenshot from 2020-01-08 12-14-43.png…]()

**Comment by mmouterde** [comment]
It was already an issue on timescaledb-1.4.2-postgresql-10.

**Comment by mmouterde** [comment]
fixed in 1.6, thanks guys

**Comment by lawzava** [comment]
Still experiencing the exact same issue with larger updates on 1.6 @mmouterde
