### ISSUE TITLE
[Bug]: error when joining two hypertables with aggregate query

### ISSUE THREAD

**Issue by cocowalla** [timescale/timescaledb#4774]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

When running aggregate queries that join two hypertables, an error occurs: `ORDER/GROUP BY expression not found in targetlist`

### TimescaleDB version affected

2.8.0 and 2.9.0-dev

### PostgreSQL version used

14.5

### What operating system did you use?

Debian Bullseye

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ORDER/GROUP BY expression not found in targetlist
```

### How can we reproduce the bug?

```bash
Before starting, ensure you are using TSDB `2.9.0-dev` (I built it from the `main` branch). This bug was somewhat apparent in 2.8.0 as well, but overlapped a lot with #4418.

## Repro 1
First, create two hypertables:


DO LANGUAGE plpgsql $tran$
    DECLARE _ret text;
BEGIN

    CREATE TABLE table_a (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        message_type      integer                     NOT NULL
    );

    CREATE TABLE table_b (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        is_authorized     boolean                     NOT NULL
    );

    SELECT * INTO _ret FROM create_hypertable('table_a', 'timestamp', create_default_indexes => true, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table A Hypertable created %', _ret;

    SELECT * INTO _ret FROM create_hypertable('table_b', 'timestamp', create_default_indexes => true, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table B Hypertable created %', _ret;

    INSERT INTO table_a (id, timestamp, message_type) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, 1);
    INSERT INTO table_b (id, timestamp, is_authorized) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, false);

END;
$tran$;


Now execute an aggregate query that uses both tables:

```sql
SELECT
    time_bucket_gapfill('1 hour', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a AS a
LEFT JOIN
    table_b AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW()
GROUP BY
    bucket
ORDER BY
    1 ASC
```

Whether an `INNER` or `LEFT` join, this will result in the error:
```
ORDER/GROUP BY expression not found in targetlist
```

## Repro 2
If we modify things slightly, using our own indices that include both the `timestamp` and `id` columns, then the issue only appears with `INNER JOIN` - not with `LEFT JOIN`.

First, create two hypertables:

```sql
DO LANGUAGE plpgsql $tran$
    DECLARE _ret text;
BEGIN

    CREATE TABLE table_a (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        message_type      integer                     NOT NULL
    );
    CREATE UNIQUE INDEX table_a_idx_timestamp ON table_a ("message_type", "timestamp" DESC, "id");

    CREATE TABLE table_b (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        is_authorized     boolean                     NOT NULL
    );
    CREATE UNIQUE INDEX table_b_idx_timestamp ON table_b ("timestamp" DESC, "id");

    SELECT * INTO _ret FROM create_hypertable('table_a', 'timestamp', create_default_indexes => false, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table A Hypertable created %', _ret;

    SELECT * INTO _ret FROM create_hypertable('table_b', 'timestamp', create_default_indexes => false, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table B Hypertable created %', _ret;

    INSERT INTO table_a (id, timestamp, message_type) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, 1);
    INSERT INTO table_b (id, timestamp, is_authorized) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, false);

END;
$tran$;
```

Now execute an aggregate query that uses both tables:

```sql
SELECT
    time_bucket_gapfill('1 hour', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a AS a
INNER JOIN
    table_b AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW()
GROUP BY
    bucket
ORDER BY
    1 ASC
```

This will result in the error:
```
ORDER/GROUP BY expression not found in targetlist
```

Note that if you include any of the joined table columns in the `WHERE` clause, it fails with `LEFT JOIN` too, e.g.:

```sql
SELECT
    time_bucket_gapfill('1 hour', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a AS a
LEFT JOIN
    table_b AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW() AND
    b.is_authorized = true
GROUP BY
    bucket
ORDER BY
    1 ASC
```
```

**Comment by cocowalla** [comment]
Related to #4418, #4760

**Comment by svenklemm** [comment]
All of the queries you posted work for me on main-branch. Are you sure you tested latest version?
```
sven@i4774_2[3476275]=# SELECT commit_hash,commit_time FROM _timescaledb_internal.get_git_commit();
               commit_hash                |      commit_time       
------------------------------------------+------------------------
 1d4b9d6977098e74ad10888c2b44e8faf187458b | 2022-09-29 10:36:02+02
(1 row)
```

**Comment by cocowalla** [comment]
> Are you sure you tested latest version?

Yes:
```
# SELECT commit_hash,commit_time FROM _timescaledb_internal.get_git_commit();
commit_hash	commit_time
1d4b9d6977098e74ad10888c2b44e8faf187458b	2022-09-29T08:36:02+00:00
```

I just tried it again, and still get the same error with repros above. I'll rebuild the Docker image and go again, in case the last few commits somehow effect this.

**Comment by cocowalla** [comment]
OK, so I have a repro available as a Docker image now.

1. `git clone https://github.com/cocowalla/tsdb-repro-4774.git`
2. `cd tsdb-repro-4774`
3. `make build`
4. `make run`

At this point you'll have a Postgres server running with TSDB 2.9.0-dev (commit `1d4b9d6977098e74ad10888c2b44e8faf187458b`). Next step is to connect to the `app` database as `postgres` (no password required) and create hypertables as before:

```sql
DO LANGUAGE plpgsql $tran$
    DECLARE _ret text;
BEGIN

    CREATE TABLE table_a (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        message_type      integer                     NOT NULL
    );

    CREATE TABLE table_b (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        is_authorized     boolean                     NOT NULL
    );

    SELECT * INTO _ret FROM create_hypertable('table_a', 'timestamp', create_default_indexes => true, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table A Hypertable created %', _ret;

    SELECT * INTO _ret FROM create_hypertable('table_b', 'timestamp', create_default_indexes => true, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table B Hypertable created %', _ret;

    INSERT INTO table_a (id, timestamp, message_type) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, 1);
    INSERT INTO table_b (id, timestamp, is_authorized) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, false);

END;
$tran$;
```

Finally, run the query, which will fail:

```sql
SELECT
    time_bucket_gapfill('1 hour', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a AS a
LEFT JOIN
    table_b AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW()
GROUP BY
    bucket
ORDER BY
    1 ASC
```

**Comment by svenklemm** [comment]
I still cannot reproduce:
```
app=# SELECT
app-#     time_bucket_gapfill('1 hour', a.timestamp) AS bucket,
app-#     COALESCE(COUNT(*), 0) AS ct
app-# FROM
app-#     table_a AS a
app-# LEFT JOIN
app-#     table_b AS b ON
app-#         b.id = a.id AND
app-#         b.timestamp = a.timestamp
app-# WHERE
app-#     a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW()
app-# GROUP BY
app-#     bucket
app-# ORDER BY
app-#     1 ASC;
         bucket         | ct
------------------------+----
 2022-09-23 14:00:00+00 |  0
 2022-09-23 15:00:00+00 |  0
 2022-09-23 16:00:00+00 |  0
 2022-09-23 17:00:00+00 |  0
 2022-09-23 18:00:00+00 |  0
 2022-09-23 19:00:00+00 |  0
 2022-09-23 20:00:00+00 |  0
 2022-09-23 21:00:00+00 |  0
 2022-09-23 22:00:00+00 |  0
 2022-09-23 23:00:00+00 |  0
 2022-09-24 00:00:00+00 |  0
 2022-09-24 01:00:00+00 |  0
 2022-09-24 02:00:00+00 |  0
 2022-09-24 03:00:00+00 |  0
 2022-09-24 04:00:00+00 |  0
 2022-09-24 05:00:00+00 |  0
 2022-09-24 06:00:00+00 |  0
 2022-09-24 07:00:00+00 |  0
 2022-09-24 08:00:00+00 |  0
 2022-09-24 09:00:00+00 |  0
 2022-09-24 10:00:00+00 |  0
 2022-09-24 11:00:00+00 |  0
 2022-09-24 12:00:00+00 |  0
 2022-09-24 13:00:00+00 |  0
 2022-09-24 14:00:00+00 |  0
 2022-09-24 15:00:00+00 |  0
 2022-09-24 16:00:00+00 |  0
 2022-09-24 17:00:00+00 |  0
 2022-09-24 18:00:00+00 |  0
 2022-09-24 19:00:00+00 |  0
 2022-09-24 20:00:00+00 |  0
 2022-09-24 21:00:00+00 |  0
 2022-09-24 22:00:00+00 |  0
 2022-09-24 23:00:00+00 |  0
 2022-09-25 00:00:00+00 |  0
 2022-09-25 01:00:00+00 |  0
 2022-09-25 02:00:00+00 |  0
 2022-09-25 03:00:00+00 |  0
 2022-09-25 04:00:00+00 |  0
 2022-09-25 05:00:00+00 |  0
 2022-09-25 06:00:00+00 |  0
 2022-09-25 07:00:00+00 |  0
 2022-09-25 08:00:00+00 |  0
 2022-09-25 09:00:00+00 |  0
 2022-09-25 10:00:00+00 |  0
 2022-09-25 11:00:00+00 |  0
 2022-09-25 12:00:00+00 |  0
 2022-09-25 13:00:00+00 |  0
 2022-09-25 14:00:00+00 |  0
 2022-09-25 15:00:00+00 |  0
 2022-09-25 16:00:00+00 |  0
 2022-09-25 17:00:00+00 |  0
 2022-09-25 18:00:00+00 |  0
 2022-09-25 19:00:00+00 |  0
 2022-09-25 20:00:00+00 |  0
 2022-09-25 21:00:00+00 |  0
 2022-09-25 22:00:00+00 |  0
 2022-09-25 23:00:00+00 |  0
 2022-09-26 00:00:00+00 |  0
 2022-09-26 01:00:00+00 |  0
 2022-09-26 02:00:00+00 |  0
 2022-09-26 03:00:00+00 |  0
 2022-09-26 04:00:00+00 |  0
 2022-09-26 05:00:00+00 |  0
 2022-09-26 06:00:00+00 |  0
 2022-09-26 07:00:00+00 |  0
 2022-09-26 08:00:00+00 |  0
 2022-09-26 09:00:00+00 |  0
 2022-09-26 10:00:00+00 |  0
 2022-09-26 11:00:00+00 |  0
 2022-09-26 12:00:00+00 |  0
 2022-09-26 13:00:00+00 |  0
 2022-09-26 14:00:00+00 |  0
 2022-09-26 15:00:00+00 |  0
app=#
```

**Comment by svenklemm** [comment]
How are you running the queries? table_a and table_b only have 1 row each is your data different?

**Comment by cocowalla** [comment]
The only data in these tables is this, simply because the error does not appear when the tables are empty:

```sql
    INSERT INTO table_a (id, timestamp, message_type) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, 1);
    INSERT INTO table_b (id, timestamp, is_authorized) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, false);
```

But, given this is a Docker image, you should really be seeing the same results as me - which got me thinking; the only thing that can differ will be how we query. I was using Azure Data Studio, and I guess you were using psql. So... I tried it wih psql, and it works just fine?! 😕 

I checked the Postgres logs, and there is one difference - Azure Data Studio silently opens a cursor prior to executing the query, e.g.

```sql
DECLARE "e402c1c5-e6ec-436c-a9e8-bebf6df7ac4c" CURSOR WITH HOLD FOR SELECT
    time_bucket_gapfill('1 hour', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a AS a
LEFT JOIN
    table_b AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW()
GROUP BY
    bucket
ORDER BY
    1 ASC
```

So, it seems #4418 is actually resolved afterall!

How do you want to proceed from here? Should I close this issue, or do you folks want to fix the problem with cursors?

**Comment by svenklemm** [comment]
I've adjusted the title, it's still a bug but severity is lower since it only occurs with cursors.

**Comment by cocowalla** [comment]
@svenklemm sorry, me again! I've been doing some more testing, and this bug has reared it's head again - without cursors.

To reproduce, create the same 2 hypertables as before:

```sql
DO LANGUAGE plpgsql $tran$
    DECLARE _ret text;
BEGIN

    CREATE TABLE table_a (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        message_type      integer                     NOT NULL
    );

    CREATE TABLE table_b (
        id                uuid                        NOT NULL,
        timestamp         timestamp with time zone    NOT NULL,
        is_authorized     boolean                     NOT NULL
    );

    SELECT * INTO _ret FROM create_hypertable('table_a', 'timestamp', create_default_indexes => true, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table A Hypertable created %', _ret;

    SELECT * INTO _ret FROM create_hypertable('table_b', 'timestamp', create_default_indexes => true, chunk_time_interval => interval '1 week');
    RAISE NOTICE 'Table B Hypertable created %', _ret;

    INSERT INTO table_a (id, timestamp, message_type) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, 1);
    INSERT INTO table_b (id, timestamp, is_authorized) VALUES ('d0295c43-752c-42e7-b2c3-f03ad2e9f4f3', current_timestamp, false);

END;
$tran$;
```

Then execute:

```sql
SELECT
    time_bucket_gapfill('1 day', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a2 AS a
LEFT JOIN
    table_b2 AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW() - INTERVAL '1 day'
GROUP BY
    bucket
ORDER BY
    1 ASC
```

It will fail with: `[XX000] ERROR: ORDER/GROUP BY expression not found in targetlist`.

The problem seems to arise when using `time_bucket_gapfill` in a query that joins multiple hypertables, where there are zero results for every `time_bucket_gapfill` bucket. Note that _some_ data does need to be in the table.

Changing the join to an `INNER JOIN` works around the issue for this _particular_ query, but I have `INNER JOIN` queries in production code that are failing the same way.

**Comment by svenklemm** [comment]
Doesnt fail for me:

```
sven@i4774[1238679]=# SELECT
    time_bucket_gapfill('1 day', a.timestamp) AS bucket,
    COALESCE(COUNT(*), 0) AS ct
FROM
    table_a AS a
LEFT JOIN
    table_b AS b ON
        b.id = a.id AND
        b.timestamp = a.timestamp
WHERE
    a.timestamp > NOW() - INTERVAL '1 week' AND a.timestamp < NOW() - INTERVAL '1 day'
GROUP BY
    bucket
ORDER BY
    1 ASC;
         bucket         | ct
------------------------+----
 2022-10-16 02:00:00+02 |  0
 2022-10-17 02:00:00+02 |  0
 2022-10-18 02:00:00+02 |  0
 2022-10-19 02:00:00+02 |  0
 2022-10-20 02:00:00+02 |  0
 2022-10-21 02:00:00+02 |  0
 2022-10-22 02:00:00+02 |  0
(7 rows)
```

**Comment by cocowalla** [comment]
@svenklemm are you running the same build as before, or a later commit? (I tested with commit 1d4b9d6977098e74ad10888c2b44e8faf187458b)

**Comment by JackMyers001** [comment]
I believe I have also run into this bug, running the latest build of the TimescaleDB Docker Container on a Linux x64 host (tag `latest-pg14`, container hash `b608d69362d4`, Timescale internal git commit `65078486025a5cfdd00663f524831619066c5946 | 2022-10-06 06:59:00+00`.)

I have three tables, created as follows:

```sql
CREATE TABLE sensors (
    sensor_id SERIAL PRIMARY KEY,
    sensor_name VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE sensor_data (
    time TIMESTAMPTZ NOT NULL,
    sensor_id INTEGER REFERENCES sensors,
    value real
);

CREATE TABLE sensor_override (
    time TIMESTAMPTZ NOT NULL,
    sensor_id INTEGER REFERENCES sensors,
    value real
);

SELECT create_hypertable('sensor_data', 'time');
SELECT create_hypertable('sensor_override', 'time');
```

I need the ability in my application to override a sensor for a period of time (e.g. if the user knows that a faulty sensor has been giving incorrect data). I have data points for my sensors every 5 seconds.

I have a query that basically says "give me all data for a given sensor in a given time period where there's no override" (i.e. the resulting graph will be continuous unless an override exists, in which case there will be gaps in the graph). The query for this is as follows:

```sql
SELECT
  time_bucket_gapfill('5s', s.time, '2022-11-20T00:00:00Z', '2022-11-22T11:50:11Z') as stime,
  AVG(s.value) as value
FROM
  sensor_data s
WHERE NOT EXISTS (
  SELECT
    NULL
  FROM
    sensor_override ov
  WHERE
    ov.time = s.time AND
    ov.sensor_id = 123 AND
    ov.time BETWEEN '2022-11-20T00:00:00Z' AND '2022-11-22T11:50:11Z'
) AND
  s.time BETWEEN '2022-11-20T00:00:00Z' AND '2022-11-22T11:50:11Z' AND
  s.sensor_id = 123
GROUP BY stime
ORDER BY 1;
```

This query _works_. **However**, if I change the end time to 11:50:10, Postgres throws an error:

```
ERROR:  ORDER/GROUP BY expression not found in targetlist
SQL state: XX000
```

Decrease the end time by a second, a minute, an hour, a day? Still errors. Bring forward the start time? Error. Make the query range bigger (i.e. 3 days)? _**Absolutely fine**_

For some reason, any query that is less than about 215,411 seconds (or 43083 points at 1 point every 5 sec) fails.

**Comment by akuzm** [comment]
> However, if I change the end time to 11:50:10, Postgres throws an error:

Still works fine for me on PG 14 and TimescaleDB 2.9.1. Maybe it's dependent on the data? I also tried eight different query plans: all chunks excluded for both tables, one of them, or none of them, in runtime or in planning time. Still no error. We need some way to reproduce this.

**Comment by noudreturn** [comment]
I seem to have the same bug in Timescale Cloud. When I increase the query time range, the error disappears.

**Comment by RafiaSabih** [comment]
@noudreturn Would you please give the complete set of steps for reproducing.

**Comment by antekresic** [comment]
Issue has been fixed by https://github.com/timescale/timescaledb/pull/6377

Thanks for reporting this!

**Comment by kyrias** [comment]
I seem to be able to still reproduce this with the latest `timescaledev/timescaledb:nightly-pg16` container image using the reduced example below.

```sql
CREATE TABLE u (id uuid primary key);
INSERT INTO u (id) values ('ad46125f-7e74-4f28-97c7-f8686cd2d012');

CREATE TABLE p (
    duration interval,
    start_time timestamptz not null,
    user_id uuid references u(id)
);
SELECT create_hypertable('p', 'start_time');
INSERT INTO p (duration, start_time, user_id) values ('02:00:00', '2023-12-14 09:01:03.91968+00', 'ad46125f-7e74-4f28-97c7-f8686cd2d012');

SELECT u.id
FROM users u
LEFT JOIN (
   SELECT FLOOR(EXTRACT (EPOCH FROM SUM(ap.duration)))::INT8 AS "total_login_seconds"
   FROM p ap
   WHERE ap.user_id = 'ad46125f-7e74-4f28-97c7-f8686cd2d012'
   GROUP BY ap.user_id
) ap ON TRUE
WHERE u.id = 'ad46125f-7e74-4f28-97c7-f8686cd2d012'
;
```

**Comment by antekresic** [comment]
Hm, I just tried it and it works fine.

Can you double-check that you pulled the latest Docker image?

Thanks,

**Comment by kyrias** [comment]
Strange, I've never pulled that image before so not sure what happened, but it does indeed seem to work after doing a `podman system reset`.

**Comment by kyrias** [comment]
Are there any estimates for when a 2.13.1 release might be cut?  This is the last thing currently blocking us from being able to upgrade to PostgreSQL 16.

**Comment by svenstaro** [comment]
I think this is a fairly important fix that should be backported and released in a patch release. After all, PostgreSQL 16 support was advertised and if bugs crop up, we shouldn't have to wait until the next minor release. Please consider this.

**Comment by jnidzwetzki** [comment]
Hi @svenstaro,

Thanks for bringing this up. I discussed this internally. We will build a patch release (2.13.1) at the beginning of January.

**Comment by xMlex** [comment]
Hello!

A have error with query:

```sql
select time_bucket('10 minutes', event_at),
       COUNT(*)       as value,
       host

from requests
WHERE event_at > now() - interval '10 minutes'
AND host in ('VM-FAST-WEB')
GROUP BY 1, host
ORDER BY 1;
```

result(error): `[XX000] ERROR: ORDER/GROUP BY expression not found in targetlist`

if exclude `AND host in ('VM-FAST-WEB')`  - no problem, query executed.
 
version:(docker) `timescale/timescaledb-ha:pg16.2-ts2.14.2-all`

Help please)

**Comment by xMlex** [comment]
on pg 15 no problem
