### ISSUE TITLE
Database rapidly slowing down in time

### ISSUE THREAD

**Issue by fesz21** [timescale/timescaledb#819]
Hi,
I tried to install timescale on our database server but find out that database is going rapidly slower in time, I had to restart it and it work again fast. 
See graph from [pgbadger](https://imgur.com/a/e4Ot9J0) - average queries duration (loging only queries with greater duration then 20ms):
- first 24h - disabled loading timescale in postgresql.conf (yes I get error in one database that timescale is not loaded) try it for one day and it was ok

- second 24h - When load timescale again it becomes slower and slower

- last 12h - I try to stop inserting in table which is using timescale

Queries is slowing down even in databases where it is not created extension of timescale.

system: Debian 9.5 in Xen domU 
postgresl: 10.5-2
timescale: 0.12.1
hardware: ZFS raidz on 4 sata disk with ssd write cache and l2arc
postgresql.conf: tuned some memorys items: shared_buffers = 4GB, temp_buffers = 64MB, work_mem = 200MB and full_page_writes=off (i believe in zfs :));

**Comment by JLockerman** [comment]
Hi,

Can you share a bit more information on your workload? Specifically, what are your SELECT and WRITE queries? Right now we don't have quite enough information to reproduce

Thank you for the bug-report!

**Comment by fesz21** [comment]
Hi,
On  one cluster we have few databases:
- with small traffic (aka mediawiki, prosody, icinga2)
- newly installed pmacct with many simple inserts (this is where I want to use timescale mainly)
- simple monitoring - loging ping reply on about 1500 hosts (many but simple inserts - again ideal for timescale; selecting in about 10s intervals data for making visual state of network)
- low traffic webbased IS - with some automatic updates 

I tried few hours ago to DROP EXTENSION timescaledb from only one database where it was created (pmacct) and only one table where hypertables was made (of course with cascade so with drop data table).
I don't restart postgresql.
Now I have loaded timescale in postgresql.conf but don't have neither one database with created extension of timescale, and in graphs I can still see growing avg. time query.

**Comment by JLockerman** [comment]
That is odd. Usually when we see inserts getting slower over time it means that the chunks are much too big, we recommend sizing chunks so that active chunks take 1/4 of main memory (see [our docs](https://docs.timescale.com/v0.12/api#create_hypertable-best-practices) for more details). Would you check the output of `chunk_relation_size_pretty` and make sure it's something sensible?

In your case it sounds like inserts get slower even when no hypertables are in use (possibly when timescaledb isn't even loaded?) which is unusual, to say the least.

**Comment by fesz21** [comment]
Hi,
sorry for late answer, I'm trying to investigate if some queries could have effect on slowing down.
To your question: virtual host has 48G RAM, maximum rows count which I have in hypertable was about 2mil. rows which can't reach recomended limit of 1/4 of main memory (whole cluster folder has about 40GB). As I wrote before I `drop extension` with all data but problem persists.

Some tests: https://imgur.com/13Zsmv9

2018-10-24 evening:
- turn off some script which make many updates (which is nice to see in graph)
- queries taking longer but maybe not so fast
- restart postgresql 

2018-10-25 morning:
- turn on script mentioned above (without postgresql restart)

2018-10-25 noon:
- restart postgresql
- so we can see that postgres is fast again but slowing down

2018-10-25 evening:
- turn off whole timescale from postgresql.conf 
- restart postgresql
=> we will see if it will slowing down

**Comment by fesz21** [comment]
without timescalen in postgresql.conf: https://imgur.com/M9f1Cnm (peek in graph is because I manualy fire vacuum db)

**Comment by fesz21** [comment]
https://imgur.com/ScLsvJG  firtst half of graph - without TS, second half wit TS in pg.conf , it's after vacuum from yesterday

**Comment by mfreed** [comment]
Hi @fesz21:

As @JLockerman suggested, could you please post the output of `chunk_relation_size_pretty`, as well as your configuration settings related to memory?  

https://docs.timescale.com/v0.12/api#chunk_relation_size_pretty

**Comment by fesz21** [comment]
Hi,
I can't send output of this function, because I have slowing down problem even if I have ONLY enabled timescale in postgresql.conf, I don't  have  `CREATE EXTENSION timescale;` in not one database. 

Here's pg_extension from only one database where I tried timescale (now extension is not active):
`pmacct=> SELECT * FROM pg_extension ;
 extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
---------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql |       10 |           11 | f              | 1.0        |           | 
(1 row)`

Please see my previous post:

> I tried few hours ago to DROP EXTENSION timescaledb from only one database where it was created (pmacct) and only one table where hypertables was made (of course with cascade so with drop data table).
> I don't restart postgresql.
> Now I have loaded timescale in postgresql.conf but don't have neither one database with created extension of timescale, and in graphs I can still see growing avg. time query.

That is weird.

Meantime I'm trying to test various changes in configuration and had to wait few hours to take effect in graph (see above), last thing I tried few hours ago is to run default debian's postgresql.conf (except some changes in logging.It's not so obviously (then from graph before) that is still slowing down.  https://imgur.com/q3rfFCL

**Comment by fesz21** [comment]
I enabled timescale 1.0.0-rc3 without creating extension with tuned memory and it seems ok - see second half of graph https://imgur.com/69v03Jc

**Comment by JLockerman** [comment]
Do the fix persist when `CREATE EXTENSION` is called?

**Comment by fesz21** [comment]
i created extension in one db few hours ago and it looks ok,I'll play with real data in next days and report behavior.

**Comment by fesz21** [comment]
after some testing with hypertable and live data on it, it looks fixed in 1.0.0-rc3, I just upgrade to 1.0.0 and I suppose it will be ok

**Comment by fesz21** [comment]
I'm on 1.0.0 and it appears again: 

memory on server: 48G
shared_buffers: 12G
avg size of chunk: about 2G ( less than suggested 1/4 of main memory)

Here is chunk_relation_size (if it's relevant):

```sql
SELECT chunk_id, table_size, index_size,toast_size, total_size FROM  chunk_relation_size_pretty('monitor_ip_live');
 chunk_id | table_size | index_size | toast_size | total_size 
----------+------------+------------+------------+------------
        1 | 72 kB      | 168 kB     | 8192 bytes | 248 kB
        2 | 72 kB      | 168 kB     | 8192 bytes | 248 kB
        3 | 64 kB      | 152 kB     | 8192 bytes | 224 kB
        4 | 64 kB      | 144 kB     | 8192 bytes | 216 kB
        5 | 623 MB     | 1150 MB    | 8192 bytes | 1773 MB
        6 | 701 MB     | 1290 MB    | 8192 bytes | 1991 MB
        7 | 597 MB     | 1103 MB    | 8192 bytes | 1700 MB
        8 | 654 MB     | 1206 MB    | 8192 bytes | 1860 MB
        9 | 744 MB     | 1369 MB    | 8192 bytes | 2113 MB
       10 | 633 MB     | 1171 MB    | 8192 bytes | 1804 MB
       11 | 662 MB     | 1221 MB    | 8192 bytes | 1883 MB
       12 | 695 MB     | 1281 MB    | 8192 bytes | 1976 MB
       13 | 745 MB     | 1388 MB    | 8192 bytes | 2133 MB
       14 | 634 MB     | 1188 MB    | 8192 bytes | 1822 MB
       15 | 663 MB     | 1239 MB    | 8192 bytes | 1901 MB
       16 | 695 MB     | 1299 MB    | 8192 bytes | 1995 MB
       17 | 753 MB     | 1573 MB    | 8192 bytes | 2326 MB
       18 | 640 MB     | 1357 MB    | 8192 bytes | 1998 MB
       19 | 670 MB     | 1411 MB    | 8192 bytes | 2080 MB
       20 | 700 MB     | 1477 MB    | 8192 bytes | 2177 MB
       21 | 749 MB     | 1568 MB    | 8192 bytes | 2317 MB
       22 | 636 MB     | 1346 MB    | 8192 bytes | 1982 MB
       23 | 667 MB     | 1405 MB    | 8192 bytes | 2072 MB
       24 | 695 MB     | 1470 MB    | 8192 bytes | 2165 MB
       25 | 669 MB     | 1400 MB    | 8192 bytes | 2069 MB
       26 | 567 MB     | 1202 MB    | 8192 bytes | 1769 MB
       27 | 595 MB     | 1254 MB    | 8192 bytes | 1850 MB
       28 | 620 MB     | 1312 MB    | 8192 bytes | 1932 MB
(28 rows)
```
Thanks for suggestions.

**Comment by mfreed** [comment]
Hi @fesz21 I have to admit I still don't quite understand the problem.  Do you have many different databases (or hypertables) on one server competing for memory resources (so the latest chunks in one hypertable can't reside in memory)?  Are you actually inserting data in time-ordered fashion, so you aren't constantly swapping in old data from disk, etc.

**Comment by ryan-shaw** [comment]
Saw that ZFS is used here, @fesz21 what's your disk usage like? ZFS devices will start to slow down when nearing ~80% capacity

**Comment by mfreed** [comment]
Hi @fesz21 Following up for more ZFS information as suggested by @ryan-shaw .  Thanks!

**Comment by dianasaur323** [comment]
@fesz21 are you still seeing this issue? Since it's been a while, I'll go ahead and close out in around a week if you aren't seeing this issue anymore.

**Comment by fesz21** [comment]
Hi, I don`t see this issue anymore, so I'm closing it.
